
apiVersion: v1
kind: Service
metadata:
  name: notes-frontend-service
  labels:
    app: notes-frontend
    tier: frontend
spec:
  selector:
    app: notes-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 30080  # Fixed NodePort for easier access
  type: NodePort  