apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-frontend
  labels:
    app: notes-frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-frontend
  template:
    metadata:
      labels:
        app: notes-frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: ${DOCKER_USERNAME}/notes-frontend:v1  # Replace with your image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: api_url
        - name: THEME_COLOR
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: theme_color
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15