apiVersion: v1
kind: Service
metadata:
  name: notes-api-service
  labels:
    app: notes-api
    tier: backend
spec:
  selector:
    app: notes-api
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP 