apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api
  labels:
    app: notes-api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
        tier: backend
    spec:
      containers:
      - name: api
        image: ${DOCKER_USERNAME}/notes-api:v1  # Replace with your image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: api_environment
        - name: API_VERSION
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: api_version
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: allowed_origins
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20